### ISSUE TITLE
Glaze compilation error with `std::variant` + `glz::object` on MSVC

### ISSUE THREAD

**Issue by sam20908** [stephenberry/glaze#1144]
Reduced repro (v2.9.5):

```cpp
struct a {
  int m1;

  struct glaze {
    static constexpr auto value = glz::object("a", &a::m1);
  };
};

struct b {
  std::vector<a> m1;
  bool m2;

  struct glaze {
    static constexpr auto value = glz::object("a", &b::m1, "b", &b::m2);
  };
};

struct c {
  std::vector<a> m1;
  struct glaze {
    static constexpr auto value = &c::m1;
  };
};

struct v_t {
  std::variant<a, b, c> m1;
  struct glaze {
    static constexpr auto value = &v_t::m1;
  };
} v;

glz::read_json(v, std::string{""});
```

**Comment by stephenberry** [comment]
I merged a similar test into `main` with #1151. This test passes on MSVC, etc.

However, I altered your example so that it is compatible with Glaze's variant deduction. Note that `a` and `b` are not auto-deducible, because `a` has a key set that is an entire subset of `b`. Because JSON allow partial objects, we have no way to determine whether the key `"a"` is relating to type `a` or type `b`.

**Comment by sam20908** [comment]
I tried compiling against your test code, and it still fails to compile for me. Perhaps we're using different MSVC version?

I'm using VS 2022 Build Tools 17.10.4 (should be same as VS 2022 17.10.4)
I'm also using latest version of Glaze 2.9.5

Here are the relevant compiler errors:
```
[build] D:\avatarCam\out\build\Debug\_deps\glaze-src\include\glaze\core\meta.hpp(132,76): error C2228: left of '.value' must have class/struct/union [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
[build] D:\avatarCam\out\build\Debug\_deps\glaze-src\include\glaze\core\meta.hpp(132,35): error C2119: 'meta_v<var_c>': the type for 'const auto' cannot be deduced from an empty initializer [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
[build] D:\avatarCam\out\build\Debug\_deps\glaze-src\include\glaze\tuplet\tuple.hpp(624,72): error C2027: use of undefined type 'glz::tuple_size<int>' [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
[build] D:\avatarCam\out\build\Debug\_deps\glaze-src\include\glaze\tuplet\tuple.hpp(624,72): error C2065: 'value': undeclared identifier [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
[build] D:\avatarCam\out\build\Debug\_deps\glaze-src\include\glaze\tuplet\tuple.hpp(624,72): error C2131: expression did not evaluate to a constant [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
[build] D:\avatarCam\out\build\Debug\_deps\glaze-src\include\glaze\core\common.hpp(667,8): error C2131: expression did not evaluate to a constant [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
[build] D:\avatarCam\out\build\Debug\_deps\glaze-src\include\glaze\core\common.hpp(674,39): error C2131: expression did not evaluate to a constant [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
[build] C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\array(419,49): error C2131: expression did not evaluate to a constant [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
[build] C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\array(420,55): error C2131: expression did not evaluate to a constant [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
[build] C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\array(572,16): error C2131: expression did not evaluate to a constant [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
[build] C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\array(303,59): error C2131: expression did not evaluate to a constant [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
[build] C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\array(43,24): error C2131: expression did not evaluate to a constant [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
[build] C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\array(305,48): error C2131: expression did not evaluate to a constant [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
[build] C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\array(316,24): error C2131: expression did not evaluate to a constant [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
[build] D:\avatarCam\out\build\Debug\_deps\glaze-src\include\glaze\core\common.hpp(685,16): error C2672: 'for_each': no matching overloaded function found [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
[build] D:\avatarCam\out\build\Debug\_deps\glaze-src\include\glaze\core\common.hpp(719,39): error C2131: expression did not evaluate to a constant [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
[build] D:\avatarCam\out\build\Debug\_deps\glaze-src\include\glaze\core\common.hpp(722,73): error C2971: 'std::make_index_sequence': template parameter '_Size': 'key_size_pair': a variable with non-static storage duration cannot be used as a non-type argument [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
[build] D:\avatarCam\out\build\Debug\_deps\glaze-src\include\glaze\json\read.hpp(2231,58): error C2131: expression did not evaluate to a constant [D:\avatarCam\out\build\Debug\AvatarCam.vcxproj]
```

**Comment by stephenberry** [comment]
Thanks for the additional info. I'll do some testing on MSVC and get back to you.

**Comment by sam20908** [comment]
Tested against version 3.0.0 and this is no longer an issue! Thanks
