### ISSUE TITLE
Compilation error because of `glaze/reflection/enum_macro.hpp`

### ISSUE THREAD

**Issue by Bolderaysky** [stephenberry/glaze#1225]
After updating glaze from `v2.6.1` to `v3.1.7`, my project no longer compiles because of this error:
```cpp
In file included from build/_deps/glaze-src/include/glaze/core/context.hpp:11,
                 from build/_deps/glaze-src/include/glaze/core/common.hpp:15,
                 from build/_deps/glaze-src/include/glaze/core/refl.hpp:6,
                 from build/_deps/glaze-src/include/glaze/json/write.hpp:12,
                 from net/http/message.hpp:10,
                 from net/http/response.hpp:5,
                 from net/http/response.cpp:1:
build/_deps/glaze-src/include/glaze/reflection/enum_macro.hpp:14:16: error: expected primary-expression before ‘(’ token
   14 |          nameof(T{})
      |                ^
In file included from build/_deps/glaze-src/include/glaze/core/context.hpp:11,
                 from build/_deps/glaze-src/include/glaze/core/common.hpp:15,
                 from build/_deps/glaze-src/include/glaze/core/refl.hpp:6,
                 from build/_deps/glaze-src/include/glaze/json/write.hpp:12,
                 from net/http/message.hpp:10,
                 from net/http/request.hpp:4,
                 from net/http/request.cpp:1:
build/_deps/glaze-src/include/glaze/reflection/enum_macro.hpp:14:16: error: expected primary-expression before ‘(’ token
   14 |          nameof(T{})
      |                ^
```
Clangd also shows similar error:
```cpp
In included file: unexpected namespace name 'nameof': expected expression
enum_macro.hpp(14, 10): Error occurred here
```

Compiler version as this may be helpful:
```
➤ g++ --version
g++ (GCC) 14.1.1 20240720
```

Downgrading to `v2.8.4` seems to resolve the issue, as `enum_macro.hpp` was introduced in `v2.9.0`

I was able to fix some of these errors by cleaning up my headers, but overall, it seems that something conflicts with glaze, as everything works in clean environment / after commenting out headers i include, and i don't see any pattern behind this problem, so not sure what can cause this behaviour. Any ideas?

**Comment by stephenberry** [comment]
Interesting, I'll have to do some experimentation to try to replicate an issue. `nameof` does use argument dependent lookup (ADL), so include order can matter. Will look into when I get a chance.

**Comment by stephenberry** [comment]
Can you try manually including `glaze/reflection/enum_macro.hpp` first in your Glaze includes? I have not been able to replicate this issue.

**Comment by stephenberry** [comment]
@Bolderaysky, I realized that the constexpr arrays these macros were generating were not declared `inline`. This may be your issue and may now be solved as of #1252 in [v3.2.2](https://github.com/stephenberry/glaze/releases/tag/v3.2.2)

**Comment by Bolderaysky** [comment]
After updating to `v3.2.2`, issue is still here. However, i experimented a little bit with headers and it seems  `glaze/reflection/get_name.hpp` was the issue in my case. Mostly likely it was included accidentally by tooling, removing this header from my includes fixes issue for me. However, including it in clean environment doesn't reproduce issue for me, so it's possible that the problem is on my side.

I will check what can be the cause of this and will let you know if I find something

**Comment by stephenberry** [comment]
I'm going to close this for now, but definitely open it back up if you run into the issue again. Thanks!
